/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Management.NGO;

/**
 *
 * @author indianrenters
 */
public class NGOAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form NGOAdminWorkArea
     */
    public NGOAdminWorkArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSystemAdminWorkArea2 = new javax.swing.JPanel();
        tabViewPanes2 = new javax.swing.JTabbedPane();
        pnlProfile2 = new javax.swing.JPanel();
        pnlManageNetwork1 = new javax.swing.JPanel();
        tblManageNetwork1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtAddNetwork1 = new javax.swing.JTextField();
        lblAddNetwork1 = new javax.swing.JLabel();
        pnlManageEnterprise1 = new javax.swing.JPanel();
        cmbNetwork1 = new javax.swing.JComboBox<>();
        lblSelectNetwork1 = new javax.swing.JLabel();
        ScrPaneManageEnterprise1 = new javax.swing.JScrollPane();
        tblManageEnterprise1 = new javax.swing.JTable();
        lblEnterpriseType1 = new javax.swing.JLabel();
        cmbEnterpriseType1 = new javax.swing.JComboBox<>();
        lblEnterpriseName1 = new javax.swing.JLabel();
        txtEnterpriseName1 = new javax.swing.JTextField();
        btnSubmit1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        pnlManageOrganisation1 = new javax.swing.JPanel();
        lblOrganisationType1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblManageOrganisations1 = new javax.swing.JTable();
        lblSelectNewtorkOrg1 = new javax.swing.JLabel();
        cmbSelectNetworkOrg1 = new javax.swing.JComboBox<>();
        btnUpdateOrg1 = new javax.swing.JButton();
        btnUpdateSubmit1 = new javax.swing.JButton();
        txtOrganisationName1 = new javax.swing.JTextField();
        lblOrganisationName1 = new javax.swing.JLabel();
        cmbOrgansiationType1 = new javax.swing.JComboBox<>();
        cmbSelectEnterpriseOrg1 = new javax.swing.JComboBox<>();
        lblSelectEnterpriseOrg1 = new javax.swing.JLabel();
        pnlUser1 = new javax.swing.JPanel();
        ScrPaneManageUsers1 = new javax.swing.JScrollPane();
        tblManageUsers1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        tabViewPanes2.setBackground(java.awt.Color.lightGray);

        pnlProfile2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlProfile2Layout = new javax.swing.GroupLayout(pnlProfile2);
        pnlProfile2.setLayout(pnlProfile2Layout);
        pnlProfile2Layout.setHorizontalGroup(
            pnlProfile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        pnlProfile2Layout.setVerticalGroup(
            pnlProfile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        tabViewPanes2.addTab("View Stats", pnlProfile2);

        pnlManageNetwork1.setBackground(new java.awt.Color(234, 253, 234));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Network ID", "Network Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManageNetwork1.setViewportView(jTable2);

        txtAddNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddNetwork1ActionPerformed(evt);
            }
        });

        lblAddNetwork1.setText("Add Network Name");

        javax.swing.GroupLayout pnlManageNetwork1Layout = new javax.swing.GroupLayout(pnlManageNetwork1);
        pnlManageNetwork1.setLayout(pnlManageNetwork1Layout);
        pnlManageNetwork1Layout.setHorizontalGroup(
            pnlManageNetwork1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageNetwork1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblManageNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageNetwork1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblAddNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(txtAddNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        pnlManageNetwork1Layout.setVerticalGroup(
            pnlManageNetwork1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageNetwork1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(tblManageNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlManageNetwork1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddNetwork1))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        tabViewPanes2.addTab("Manage Network", pnlManageNetwork1);

        pnlManageEnterprise1.setBackground(new java.awt.Color(255, 230, 255));

        cmbNetwork1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "New York", "Massachussetts" }));
        cmbNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetwork1ActionPerformed(evt);
            }
        });

        lblSelectNetwork1.setText("Select Network");

        tblManageEnterprise1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise ID", "Enterprise", "Enterprise Type"
            }
        ));
        ScrPaneManageEnterprise1.setViewportView(tblManageEnterprise1);

        lblEnterpriseType1.setText("Enterprise Type");

        cmbEnterpriseType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEnterpriseName1.setText("Enterprise Name");

        txtEnterpriseName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterpriseName1ActionPerformed(evt);
            }
        });

        btnSubmit1.setText("Submit");

        btnUpdate1.setText("Update");

        javax.swing.GroupLayout pnlManageEnterprise1Layout = new javax.swing.GroupLayout(pnlManageEnterprise1);
        pnlManageEnterprise1.setLayout(pnlManageEnterprise1Layout);
        pnlManageEnterprise1Layout.setHorizontalGroup(
            pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                        .addComponent(btnUpdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit1))
                    .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                            .addGap(265, 265, 265)
                            .addComponent(lblSelectNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(ScrPaneManageEnterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEnterpriseName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEnterpriseType1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEnterpriseName1)
                                .addComponent(cmbEnterpriseType1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        pnlManageEnterprise1Layout.setVerticalGroup(
            pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageEnterprise1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectNetwork1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrPaneManageEnterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1)
                    .addComponent(btnSubmit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseType1)
                    .addComponent(cmbEnterpriseType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlManageEnterprise1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName1)
                    .addComponent(txtEnterpriseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        tabViewPanes2.addTab("Manage Enterprise", pnlManageEnterprise1);

        pnlManageOrganisation1.setBackground(new java.awt.Color(204, 204, 255));

        lblOrganisationType1.setText("Organisation Type");

        tblManageOrganisations1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Organisation ID", "Organisation Name", "Organisation Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblManageOrganisations1);

        lblSelectNewtorkOrg1.setText("Select Network");

        cmbSelectNetworkOrg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "New York", "Massachussetts" }));

        btnUpdateOrg1.setText("Update");
        btnUpdateOrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrg1ActionPerformed(evt);
            }
        });

        btnUpdateSubmit1.setText("Submit");

        txtOrganisationName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganisationName1ActionPerformed(evt);
            }
        });

        lblOrganisationName1.setText("Organisation Name");

        cmbOrgansiationType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSelectEnterpriseOrg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supply Unit", "Transportation Unit" }));

        lblSelectEnterpriseOrg1.setText("Select Enterprise");

        javax.swing.GroupLayout pnlManageOrganisation1Layout = new javax.swing.GroupLayout(pnlManageOrganisation1);
        pnlManageOrganisation1.setLayout(pnlManageOrganisation1Layout);
        pnlManageOrganisation1Layout.setHorizontalGroup(
            pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                                .addComponent(btnUpdateOrg1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateSubmit1))
                            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                                .addComponent(lblSelectNewtorkOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSelectNetworkOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lblSelectEnterpriseOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSelectEnterpriseOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                                .addComponent(lblOrganisationName1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtOrganisationName1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                                .addComponent(lblOrganisationType1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(cmbOrgansiationType1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        pnlManageOrganisation1Layout.setVerticalGroup(
            pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageOrganisation1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSelectNetworkOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectNewtorkOrg1)
                    .addComponent(cmbSelectEnterpriseOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectEnterpriseOrg1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateOrg1)
                    .addComponent(btnUpdateSubmit1))
                .addGap(27, 27, 27)
                .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganisationType1)
                    .addComponent(cmbOrgansiationType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlManageOrganisation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganisationName1)
                    .addComponent(txtOrganisationName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabViewPanes2.addTab("Manage Organisations", pnlManageOrganisation1);

        pnlUser1.setBackground(new java.awt.Color(229, 252, 253));

        tblManageUsers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User ID", "User Name", "Password"
            }
        ));
        ScrPaneManageUsers1.setViewportView(tblManageUsers1);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ScrPaneManageUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ScrPaneManageUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        tabViewPanes2.addTab("Manage Users", pnlUser1);

        javax.swing.GroupLayout pnlSystemAdminWorkArea2Layout = new javax.swing.GroupLayout(pnlSystemAdminWorkArea2);
        pnlSystemAdminWorkArea2.setLayout(pnlSystemAdminWorkArea2Layout);
        pnlSystemAdminWorkArea2Layout.setHorizontalGroup(
            pnlSystemAdminWorkArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSystemAdminWorkArea2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tabViewPanes2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlSystemAdminWorkArea2Layout.setVerticalGroup(
            pnlSystemAdminWorkArea2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSystemAdminWorkArea2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabViewPanes2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NGO Admin Work Area");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSystemAdminWorkArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSystemAdminWorkArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddNetwork1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddNetwork1ActionPerformed

    private void cmbNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetwork1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNetwork1ActionPerformed

    private void txtEnterpriseName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterpriseName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterpriseName1ActionPerformed

    private void btnUpdateOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateOrg1ActionPerformed

    private void txtOrganisationName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganisationName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganisationName1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrPaneManageEnterprise1;
    private javax.swing.JScrollPane ScrPaneManageUsers1;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdateOrg1;
    private javax.swing.JButton btnUpdateSubmit1;
    private javax.swing.JComboBox<String> cmbEnterpriseType1;
    private javax.swing.JComboBox<String> cmbNetwork1;
    private javax.swing.JComboBox<String> cmbOrgansiationType1;
    private javax.swing.JComboBox<String> cmbSelectEnterpriseOrg1;
    private javax.swing.JComboBox<String> cmbSelectNetworkOrg1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAddNetwork1;
    private javax.swing.JLabel lblEnterpriseName1;
    private javax.swing.JLabel lblEnterpriseType1;
    private javax.swing.JLabel lblOrganisationName1;
    private javax.swing.JLabel lblOrganisationType1;
    private javax.swing.JLabel lblSelectEnterpriseOrg1;
    private javax.swing.JLabel lblSelectNetwork1;
    private javax.swing.JLabel lblSelectNewtorkOrg1;
    private javax.swing.JPanel pnlManageEnterprise1;
    private javax.swing.JPanel pnlManageNetwork1;
    private javax.swing.JPanel pnlManageOrganisation1;
    private javax.swing.JPanel pnlProfile2;
    private javax.swing.JPanel pnlSystemAdminWorkArea2;
    private javax.swing.JPanel pnlUser1;
    private javax.swing.JTabbedPane tabViewPanes2;
    private javax.swing.JTable tblManageEnterprise1;
    private javax.swing.JScrollPane tblManageNetwork1;
    private javax.swing.JTable tblManageOrganisations1;
    private javax.swing.JTable tblManageUsers1;
    private javax.swing.JTextField txtAddNetwork1;
    private javax.swing.JTextField txtEnterpriseName1;
    private javax.swing.JTextField txtOrganisationName1;
    // End of variables declaration//GEN-END:variables
}
